# Generated by Django 4.1 on 2022-10-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdensblog_mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
