# Generated by Django 4.1 on 2022-10-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdensblog_mainApp', '0004_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
