# Generated by Django 4.1 on 2022-10-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdensblog_mainApp', '0008_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
