# Generated by Django 4.1 on 2022-10-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdensblog_mainApp', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
